# Generated by Django 4.0.10 on 2025-04-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='prefering_users', to='core.tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_activity',
            field=models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('moderate', 'Moderate'), ('high', 'High')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_time', models.DateTimeField(auto_now=True, null=True)),
                ('recipes', models.ManyToManyField(blank=True, to='core.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
