# Generated by Django 4.0.10 on 2025-04-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_of_birth_user_dietary_preferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('regular', 'Regular Day'), ('workout', 'Workout Day'), ('rest', 'Rest Day')], default='regular', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.mealplan')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('mid_morning', 'Mid Morning'), ('lunch', 'Lunch'), ('mid_afternoon', 'Mid Afternoon'), ('dinner', 'Dinner'), ('supper', 'Supper'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=20)),
                ('meal_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.mealplanday')),
                ('recipes', models.ManyToManyField(blank=True, to='core.recipe')),
            ],
        ),
    ]
