# Generated by Django 4.0.10 on 2025-05-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mealplanday_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('mid_morning', 'Mid Morning'), ('lunch', 'Lunch'), ('mid_afternoon', 'Mid Afternoon'), ('dinner', 'Dinner'), ('supper', 'Supper'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='recipes',
        ),
        migrations.CreateModel(
            name='MealPartRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealpartrecipe_set', to='core.meal')),
                ('meal_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mealpart')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
            ],
        ),
    ]
