# Generated by Django 4.0.10 on 2025-05-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_average_rating_recipe_global_cooked_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('cooked_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('last_interacted_on', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
